<?php
$var1=$_POST['form_1_1'];
$var2=$_POST['form_1_2'];
$var3=$_POST['form_1_3'];
$var4=$_POST['form_1_4'];
$var5=$_POST['form_1_5'];
$var6=$_POST['form_1_6'];
$var7=$_POST['form_1_7'];
$var8=$_POST['form_1_8'];
$var9=$_POST['form_1_9'];
$var10=$_POST['form_1_10'];
$var11=$_POST['form_1_11'];
$var12=$_POST['form_1_12'];
$var13=$_POST['form_1_13'];
$var14=$_POST['form_1_14'];
$var15=$_POST['form_1_15'];
$var16=$_POST['form_1_16'];
$var17=$_POST['form_1_17'];
$var18=$_POST['form_1_18'];
$var19=$_POST['form_1_19'];
$var20=$_POST['form_1_20'];
$var21=$_POST['form_1_21'];
$var22=$_POST['form_1_22'];
$var23=$_POST['form_1_23'];
$var24=$_POST['form_1_24'];
$var25=$_POST['form_1_25'];
$var26=$_POST['form_1_26'];
$var27=$_POST['form_1_27'];
$var28=$_POST['form_1_about'];
$var29=$_POST['form_2_1'];
$var30=$_POST['form_2_2'];
$var31=$_POST['form_2_3'];
$var32=$_POST['form_2_4'];
$var33=$_POST['form_2_about'];
$var34=$_POST['form_3_1'];
$var35=$_POST['form_3_2'];
$var36=$_POST['form_3_3'];
$var37=$_POST['form_3_4'];
$var38=$_POST['form_3_5'];
$var39=$_POST['form_3_6'];
$var40=$_POST['form_3_7'];
$var41=$_POST['form_3_8'];
$var42=$_POST['form_3_9'];
$var43=$_POST['form_3_about'];
$var44=$_POST['form_4_1'];
$var45=$_POST['form_4_2'];
$var46=$_POST['form_4_3'];
$var47=$_POST['form_4_4'];
$var48=$_POST['form_4_5'];
$var49=$_POST['form_4_6'];
$var50=$_POST['form_4_7'];
$var51=$_POST['form_4_8'];
$var52=$_POST['form_4_9'];
$var53=$_POST['form_4_10'];
$var54=$_POST['form_4_11'];
$var55=$_POST['form_4_12'];
$var56=$_POST['form_4_13'];
$var57=$_POST['form_4_14'];
$var58=$_POST['form_4_15'];
$var59=$_POST['form_4_16'];
$var60=$_POST['form_4_about'];
$var61=$_POST['form_5_1'];
$var62=$_POST['form_5_about'];
$var63=$_POST['form_6_1'];
$var64=$_POST['form_6_2'];
$var65=$_POST['form_6_about'];

ECHO "ZONA 1";echo"<br>";
ECHO"Variable (1)";echo"<br>";echo$var1;echo"<br>";
ECHO"Variable (2)";echo"<br>";echo$var2;echo"<br>";
ECHO"Variable (3)";echo"<br>";echo$var3;echo"<br>";
ECHO"Variable (4)";echo"<br>";echo$var4;echo"<br>";
ECHO"Variable (5)";echo"<br>";echo$var5;echo"<br>";
ECHO"Variable (6)";echo"<br>";echo$var6;echo"<br>";
ECHO"Variable (7)";echo"<br>";echo$var7;echo"<br>";
ECHO"Variable (8)";echo"<br>";echo$var8;echo"<br>";
ECHO"Variable (9)";echo"<br>";echo$var9;echo"<br>";
ECHO"Variable (10)";echo"<br>";echo$var10;echo"<br>";
ECHO"Variable (11)";echo"<br>";echo$var11;echo"<br>";
ECHO"Variable (12)";echo"<br>";echo$var12;echo"<br>";
ECHO"Variable (13)";echo"<br>";echo$var13;echo"<br>";
ECHO"Variable (14)";echo"<br>";echo$var14;echo"<br>";
ECHO"Variable (15)";echo"<br>";echo$var15;echo"<br>";
ECHO"Variable (16)";echo"<br>";echo$var16;echo"<br>";
ECHO"Variable (17)";echo"<br>";echo$var17;echo"<br>";
ECHO"Variable (18)";echo"<br>";echo$var18;echo"<br>";
ECHO"Variable (19)";echo"<br>";echo$var19;echo"<br>";
ECHO"Variable (20)";echo"<br>";echo$var20;echo"<br>";
ECHO"Variable (21)";echo"<br>";echo$var21;echo"<br>";
ECHO"Variable (22)";echo"<br>";echo$var22;echo"<br>";
ECHO"Variable (23)";echo"<br>";echo$var23;echo"<br>";
ECHO"Variable (24)";echo"<br>";echo$var24;echo"<br>";
ECHO"Variable (25)";echo"<br>";echo$var25;echo"<br>";
ECHO"Variable (26)";echo"<br>";echo$var26;echo"<br>";
ECHO"Variable (27)";echo"<br>";echo$var27;echo"<br>";
ECHO"Variable (28)";echo"<br>";echo$var28;echo"<br>";
ECHO "ZONA 2";echo"<br>";
ECHO"Variable (29)";echo"<br>";echo$var29;echo"<br>";
ECHO"Variable (30)";echo"<br>";echo$var30;echo"<br>";
ECHO"Variable (31)";echo"<br>";echo$var31;echo"<br>";
ECHO"Variable (32)";echo"<br>";echo$var32;echo"<br>";
ECHO"Variable (33)";echo"<br>";echo$var33;echo"<br>";
ECHO "ZONA 3";echo"<br>";
ECHO"Variable (34)";echo"<br>";echo$var34;echo"<br>";
ECHO"Variable (35)";echo"<br>";echo$var35;echo"<br>";
ECHO"Variable (36)";echo"<br>";echo$var36;echo"<br>";
ECHO"Variable (37)";echo"<br>";echo$var37;echo"<br>";
ECHO"Variable (38)";echo"<br>";echo$var38;echo"<br>";
ECHO"Variable (39)";echo"<br>";echo$var39;echo"<br>";
ECHO"Variable (40)";echo"<br>";echo$var40;echo"<br>";
ECHO"Variable (41)";echo"<br>";echo$var41;echo"<br>";
ECHO"Variable (42)";echo"<br>";echo$var42;echo"<br>";
ECHO"Variable (43)";echo"<br>";echo$var43;echo"<br>";
ECHO "ZONA 4";echo"<br>";
ECHO"Variable (44)";echo"<br>";echo$var44;echo"<br>";
ECHO"Variable (45)";echo"<br>";echo$var45;echo"<br>";
ECHO"Variable (46)";echo"<br>";echo$var46;echo"<br>";
ECHO"Variable (47)";echo"<br>";echo$var47;echo"<br>";
ECHO"Variable (48)";echo"<br>";echo$var48;echo"<br>";
ECHO"Variable (49)";echo"<br>";echo$var49;echo"<br>";
ECHO"Variable (50)";echo"<br>";echo$var50;echo"<br>";
ECHO"Variable (51)";echo"<br>";echo$var51;echo"<br>";
ECHO"Variable (52)";echo"<br>";echo$var52;echo"<br>";
ECHO"Variable (53)";echo"<br>";echo$var53;echo"<br>";
ECHO"Variable (54)";echo"<br>";echo$var54;echo"<br>";
ECHO"Variable (55)";echo"<br>";echo$var55;echo"<br>";
ECHO"Variable (56)";echo"<br>";echo$var56;echo"<br>";
ECHO"Variable (57)";echo"<br>";echo$var57;echo"<br>";
ECHO"Variable (58)";echo"<br>";echo$var58;echo"<br>";
ECHO"Variable (59)";echo"<br>";echo$var59;echo"<br>";
ECHO"Variable (60)";echo"<br>";echo$var60;echo"<br>";
ECHO "ZONA 5";echo"<br>";
ECHO"Variable (61)";echo"<br>";echo$var61;echo"<br>";
ECHO"Variable (62)";echo"<br>";echo$var62;echo"<br>";
ECHO "ZONA 6";echo"<br>";
ECHO"Variable (63)";echo"<br>";echo$var63;echo"<br>";
ECHO"Variable (64)";echo"<br>";echo$var64;echo"<br>";
ECHO"Variable (65)";echo"<br>";echo$var65;echo"<br>";
?>